DRAFT PR: Added catalog and schema level access checks in USE statement
annmegha/presto pull request #4
Opened 2024-06-13 13:57 UTC by annmegha

## Description

Added catalog and schema level access checks when a user tries USE statement

## Motivation and Context

Earlier a user who do not have access to a catalog/schema when performed the USE statement it was successful. Now if the user is restricted to a schema/catalog the query will throw an Access denied error message.

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-06-17 05:32 UTC, elbinpallimalilibm approved these changes

2024-09-27 15:04 UTC, tdcmeehan requested changes
Please add a unit test

2024-09-27 15:04 UTC, tdcmeehan commented on presto-main/src/main/java/com/facebook/presto/execution/UseTask.java
> +                    .orElseGet(() -> session.getCatalog().get());
```suggestion
                    .orElse(() -> session.getCatalog());
```

2024-10-17 16:21 UTC, annmegha commented
Hi @tdcmeehan i have added the test cases, can you please review.

2024-10-17 16:35 UTC, tdcmeehan approved these changes

2024-10-24 08:44 UTC, merged